name: whoami
type: container
container:
  image: docker.io/traefik/whoami:latest
  label:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
  publish:
    - "8080:80"
