# Container unit
name: whoami-container
type: container
systemd:
  description: "Whoami container service"
  after: ["network.target"]
  restart_policy: "always"
container:
  image: docker.io/traefik/whoami
  label:
    - "app=whoami"
  publish:
    - "8080:80"

---
# Volume unit
name: whoami-volume
type: volume
systemd:
  description: "Persistent volume for whoami"
volume:
  label:
    - "app=whoami"
    - "environment=dev"

---
# Network unit
name: whoami-network
type: network
systemd:
  description: "Network for whoami services"
network:
  label:
    - "network=whoami"

---
# Pod unit
name: whoami-pod
type: pod
systemd:
  description: "Pod for whoami services"
pod:
  label:
    - "app=whoami"
    - "environment=dev"

---
# Kube unit
name: whoami-kube
type: kube
systemd:
  description: "Kubernetes deployment for whoami"
kube:
  path: "/etc/whoami/deployment.yaml"

---
# Image unit
name: whoami-image
type: image
systemd:
  description: "Whoami container image"
image:
  image: "docker.io/traefik/whoami"

---
# Build unit
name: whoami-build
type: build
systemd:
  description: "Whoami container build"
build:
  context: "./src"
  dockerfile: "Dockerfile"
